server:
  port: 8801

spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

turbine:
  app-config: feignclient
  cluster-name-expression: new String("default")
  combine-host-port: true
